// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAyvQ2BntjlJsJuA8em78_4Xq-aa4SUAM',
    appId: '1:698873459124:web:2fc8e3d7a74095c51082e1',
    messagingSenderId: '698873459124',
    projectId: 'abaixaai-11a02',
    authDomain: 'abaixaai-11a02.firebaseapp.com',
    storageBucket: 'abaixaai-11a02.firebasestorage.app',
    measurementId: 'G-V8HVS2XGMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8kGssJirdYZB5tTiwRATSsJLLeAuqzFI',
    appId: '1:698873459124:android:3ad4bc76ee0e1a341082e1',
    messagingSenderId: '698873459124',
    projectId: 'abaixaai-11a02',
    storageBucket: 'abaixaai-11a02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Pdi8rZDrrZtyCn6ygHAdfgy8bLjD4S0',
    appId: '1:698873459124:ios:3053122cd20b835c1082e1',
    messagingSenderId: '698873459124',
    projectId: 'abaixaai-11a02',
    storageBucket: 'abaixaai-11a02.firebasestorage.app',
    iosBundleId: 'com.example.abaixaai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8Pdi8rZDrrZtyCn6ygHAdfgy8bLjD4S0',
    appId: '1:698873459124:ios:3053122cd20b835c1082e1',
    messagingSenderId: '698873459124',
    projectId: 'abaixaai-11a02',
    storageBucket: 'abaixaai-11a02.firebasestorage.app',
    iosBundleId: 'com.example.abaixaai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAyvQ2BntjlJsJuA8em78_4Xq-aa4SUAM',
    appId: '1:698873459124:web:ef966985c6e2443c1082e1',
    messagingSenderId: '698873459124',
    projectId: 'abaixaai-11a02',
    authDomain: 'abaixaai-11a02.firebaseapp.com',
    storageBucket: 'abaixaai-11a02.firebasestorage.app',
    measurementId: 'G-L4LNK082FM',
  );
}
